### ISSUE TITLE
public function cancelFromAvalara not using DB prefix

### ISSUE THREAD

**Issue by alex974** [nurelm/prestashop-avalaratax#3]
Like the title said , an sql is not using the dbprefix in cancelfrom Avalara which will cause anyone who had not use prestashop default prefix to hit an error upon any orders cancelation call.

**$hasRefund = Db::getInstance()->ExecuteS('SELECT COUNT(`id_order`) as qtyProductRefunded
                                                FROM `ps_order_detail`**

Should be change to **FROM `'._DB_PREFIX_.'order_detail`**

**Comment by shaabans** [comment]
Great advice, thanks for bringing this up, we'll take care of this.
